apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-frik
  name: test-frik
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-frik
  template:
    metadata:
      labels:
        app: test-frik
    spec:
      containers:
      - image: httpd
        name: httpd
  strategy:
    type: Recreate
